import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
    id: root

    function generate(Colors) {
        if (!Colors) return

        const fmt = (c) => c.toString()

        const primary = fmt(Colors.primary)
        const onPrimary = fmt(Colors.overPrimary)
        const background = fmt(Colors.background)
        const onBackground = fmt(Colors.overBackground)
        const surface = fmt(Colors.surface)
        const onSurface = fmt(Colors.overSurface)
        const surfaceContainer = fmt(Colors.surfaceContainer)

        let css = "/* GTK Colors generated by Ambxst */\n\n"
        
        css += `@define-color accent_color ${primary};\n`
        css += `@define-color accent_fg_color ${onPrimary};\n`
        css += `@define-color accent_bg_color ${primary};\n`
        css += `@define-color window_bg_color ${background};\n`
        css += `@define-color window_fg_color ${onBackground};\n`
        css += `@define-color headerbar_bg_color ${background};\n`
        css += `@define-color headerbar_fg_color ${onBackground};\n`
        css += `@define-color popover_bg_color ${surface};\n`
        css += `@define-color popover_fg_color ${onSurface};\n`
        css += `@define-color view_bg_color ${background};\n`
        css += `@define-color view_fg_color ${onBackground};\n`
        css += `@define-color card_bg_color ${surfaceContainer};\n`
        css += `@define-color card_fg_color ${onSurface};\n`
        
        // Sidebar typically matches window or has slight contrast. 
        // Using window variables as reference.
        css += `@define-color sidebar_bg_color @window_bg_color;\n`
        css += `@define-color sidebar_fg_color @window_fg_color;\n`
        css += `@define-color sidebar_border_color @window_bg_color;\n`
        css += `@define-color sidebar_backdrop_color @window_bg_color;\n`

        const home = Quickshell.env("HOME")
        const gtk3Dir = home + "/.config/gtk-3.0"
        const gtk4Dir = home + "/.config/gtk-4.0"

        writer.text = css
        
        // Write to GTK 3/4 and reload theme
        const cmd = `
            mkdir -p "${gtk3Dir}" "${gtk4Dir}" && \\
            echo "${css}" | tee "${gtk3Dir}/gtk.css" "${gtk4Dir}/gtk.css" > /dev/null && \\
            gsettings set org.gnome.desktop.interface gtk-theme "" && \\
            gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3
        `
        
        writerProcess.command = ["sh", "-c", cmd]
        writerProcess.running = true
    }

    property QtObject writer: QtObject {
        id: writer
        property string text
    }

    property Process writerProcess: Process {
        id: writerProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("GtkGenerator: Colors generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: (err) => {
                if (err) console.error("GtkGenerator Error:", err)
            }
        }
    }
}
